# This file created by conda-build 3.13.0
# meta.yaml template originally from:
# C:\ci\containers\00002mf1b71\tmp\build\80754af9\rsync-recipes\expat-2.2.5-cxx_compiler_vs2015-c_compiler_vs2015-vc_14-on-winbuilder, last modified Tue Aug 28 15:26:53 2018
# ------------------------------------------------

package:
    name: expat
    version: 2.2.5
source:
    sha256: d9dc32efba7e74f788fcc4f212a43216fc37cf5f23f4c2339664d473353aedf6
    url: https://github.com/libexpat/libexpat/releases/download/R_2_2_5/expat-2.2.5.tar.bz2
build:
    number: '0'
    run_exports:
        - expat >=2.2.5,<3.0a0
    string: he025d50_0
requirements:
    build:
        - cmake 3.11.1 h0c2ffe5_1
        - vc 14.1 h21ff451_3
        - vs2015_runtime 15.5.2 3
        - vs2015_win-64 14.0.25123 h17c34da_3
    host:
        - vc 14.1 h21ff451_3
        - vs2015_runtime 15.5.2 3
    run:
        - vc 14.*
test:
    commands:
        - xmlwf -h
about:
    home: http://expat.sourceforge.net/
    license: MIT
    license_file: COPYING
    summary: Expat XML parser library in C.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - kwilcox
        - mingwandroid
        - msarahan
        - ocefpaf
        - pelson
