# This file created by conda-build 3.15.1
# meta.yaml template originally from:
# C:\ci\containers\0000271clai\tmp\build\80754af9\rsync-recipes\xerces-c-3.2.2-c_compiler_vs2017-cxx_compiler_vs2017-on-winbuilder, last modified Tue Oct 16 17:50:59 2018
# ------------------------------------------------

package:
    name: xerces-c
    version: 3.2.2
source:
    sha256: dd6191f8aa256d3b4686b64b0544eea2b450d98b4254996ffdfe630e0c610413
    url: https://archive.apache.org/dist/xerces/c/3/sources/xerces-c-3.2.2.tar.gz
build:
    number: '0'
    run_exports:
        - xerces-c >=3.2.2,<3.3.0a0
    string: ha925a31_0
requirements:
    build:
        - cmake 3.12.2 he025d50_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
        - vs2017_win-64 19.15.26726 h3c6f0ee_0
    host:
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_0
    run:
        - vc >=14.1,<15.0a0
about:
    home: http://xerces.apache.org/xerces-c/
    license: Apache 2.0
    license_family: Apache
    license_file: LICENSE
    summary: Xerces-C++ is a validating XML parser written in a portable subset of
        C++.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - gillins
        - groutr
        - ocefpaf
